### ISSUE TITLE
wildly different guid's

### ISSUE THREAD

**Issue by spencerbutler** [mlsmithjr/plex-watchlist-migration#1]
This script is pretty great and very fast, thanks for making it available. 

I'm migrating my plex to a new server, and following the [official plex documentation](https://support.plex.tv/articles/201154527-move-viewstate-ratings-from-one-install-to-another/) for moving watchlist/settings didn't seem to do much, if anything. I was able to export my old library with this script, it found thousands of records.  When I imported those into the new server (the plex container stopped) It only managed to update ~65 records.

I did an export of the new database to compare guid's and they are very, very different.  I'm going to see if there is anything I can hack in your script, or some sed magic I can perform on the json file to update the missing records. If you have any ideas on how I can approach this problem, I'm all ears.

Here is a brief synopsis of the differing `guid` keys.

The old plex databse.
```sh
spencer@nuc-1 ~/docker/plex/import-plex-library $ cat plex-library-2021-01-20.json | jq '.users[0].watchlist[].guid' | head
"com.plexapp.agents.thetvdb://75978/1/2?lang=en"
"com.plexapp.agents.thetvdb://75978/1/3?lang=en"
"com.plexapp.agents.thetvdb://75978/1/4?lang=en"
"com.plexapp.agents.thetvdb://71663/32/8?lang=en"
"com.plexapp.agents.thetvdb://71663/32/11?lang=en"
"com.plexapp.agents.thetvdb://161511/10/1?lang=en"
"com.plexapp.agents.thetvdb://161511/10/2?lang=en"
"com.plexapp.agents.thetvdb://75978/1/5?lang=en"
"com.plexapp.agents.thetvdb://75978/1/6?lang=en"
"com.plexapp.agents.thetvdb://75978/1/5?lang=en"
```

The new plex database.
```sh
spencer@nuc-1 ~/docker/plex/import-plex-library $ cat export-local.json | jq '.users[0].watchlist[].guid' | head
"plex://episode/5d9c127d705e7a001e75f600"
"plex://episode/5d9c127d7b5c2e001e6c7ced"
"plex://episode/5d9c127d4eefaa001f6448d7"
"plex://episode/5d9c127d705e7a001e75f618"
"plex://episode/5d9c127d08fddd001f316ca1"
"plex://episode/5d9c127d6c3e37001ecfede1"
"plex://episode/5d9c127de264b7001fcaae87"
"plex://episode/60d35eb31b6263002c8bdd33"
"plex://movie/5d77684e6f4521001eaa0974"
"plex://movie/5d776d31fb0d55001f599a2b"
```

I'm thinking the about output is probably not very helpful. I drilled down to one episode. It looks like the only difference in the 2 entries is the `library_section_id`. The top entry is from the new install, and the bottom from the old plex database.j

```json
{
  "account_id": 1,
  "guid": "plex://episode/618fb873af74f1792264cd57",
  "metadata_type": 4,
  "library_section_id": 2,
  "grandparent_title": "Equalizer",
  "parent_index": 2,
  "parent_title": "",
  "'index'": "index",
  "title": "Separated",
  "thumb_url": "metadata://posters/tv.plex.agents.series_ec826378ec864573edf4696ec3ee215858448603",
  "viewed_at": "2022-01-03 17:10:27",
  "grandparent_guid": "plex://show/5e16225ea304a6004142aa90",
  "originally_available_at": "2022-01-02 00:00:00"
}
{
  "account_id": 1,
  "guid": "plex://episode/618fb873af74f1792264cd57",
  "metadata_type": 4,
  "library_section_id": 3,
  "grandparent_title": "Equalizer",
  "parent_index": 2,
  "parent_title": "",
  "'index'": "index",
  "title": "Separated",
  "thumb_url": "metadata://posters/tv.plex.agents.series_ec826378ec864573edf4696ec3ee215858448603",
  "viewed_at": "2022-01-03 17:10:27",
  "grandparent_guid": "plex://show/5e16225ea304a6004142aa90",
  "originally_available_at": "2022-01-02 00:00:00"
}
```

When I look at the `view play history` for the episode, I see some of the data. The show does not have the "watched" attribute when viewing the item. 

![plex-media-import-debug](https://user-images.githubusercontent.com/5126075/150611899-a320e9eb-1391-40c1-a890-58805d4d17ab.png)

**Comment by mlsmithjr** [comment]
Yeah this is pretty common.  Your old server is still using the legacy metadata search engine (com.plexapp.agents.thetvdb).  To make them match you have to force a rescan of everything using the new Plex scanner (found in setup).  After this is done your guids will follow their new standard and be more compatible.

Also make sure your users are setup in the new system before importing, using the same exact names.  There is no reliable key between the 2 db’s for those so it’s a name match only.  
You also need to have all your new media collections created with the same names (same reason).

**Comment by spencerbutler** [comment]
Thanks for the response. I'll see if I can revive the old server. For some reason, when I added the new server, plex decided it didn't want to have anything to do with the old one. The mess of Plex's Let's Encrypt cert's and my LE certs served through a load balancer is just not playing well together.

**Comment by mlsmithjr** [comment]
You *may* be able to bring the .db up on your new Plex server if all the path mappings are the same.

**Comment by spencerbutler** [comment]
I wound up restoring it with the old db, which somehow corrupted it. So I learned how to repair a corrupted "Plex SQLite" database. It's working now and I'm never touching that container again 😄
