### ISSUE TITLE
KeyError: 'newid'

### ISSUE THREAD

**Issue by dan3805** [mlsmithjr/plex-watchlist-migration#2]
when I run the script to inport , the script start and stop there 

Traceback (most recent call last):
  File "watchlist.py", line 252, in <module>
    do_import(sys.argv[2], sys.argv[3])
  File "watchlist.py", line 172, in do_import
    library_section_id = source_sections[library_section_id]["newid"]
KeyError: 'newid'

**Comment by ghost** [comment]
I did a little quickfix for this - replace line 172 with:
```
if source_sections[library_section_id].get("newid") is not None:
    library_section_id = source_sections[library_section_id]["newid"]
else:
    print('  newid not found in source sections for library section id {}'.format(library_section_id))
    continue
```

**Comment by mlsmithjr** [comment]
Thanks for reporting and fixing this.  I've incorporated it into the code.
