### ISSUE TITLE
Sync does not work

### ISSUE THREAD

**Issue by inject3d** [mlsmithjr/plex-watchlist-migration#3]
Hi,

First, thanks for your script. :-)

I just tried it myself but does not work:
- First try: Executed it on the old instance and then imported it on the new instance -> Error as you described as agent was changed. I think all entries have been skipped
- Second try after updating the complete metadata: Just a handfull of entries are skipped. Looks better.

But when I try to compare the watch status is still shows that entries are not watched. I tried this when plex was started and also one try where the original docker container was stopped. Afterwards it just shows everything as new.

```
The export looks like this:
Exporting for user 123
123 watched items
export complete, results in export.json
```

```
The import looks like this:
Processing user 123
[...]
No updates for 123
```

Do you have an idea?

**Comment by mlsmithjr** [comment]
I’ll try it myself.  It could be Plex changed something in their schema but I’ll verify and get back to you.

**Comment by mlsmithjr** [comment]
Well sure enough I had a bug - a sloppy one at that.
I’ve pushed up a fix.  Sorry about that.
I tested against my failover server, which was about 3 months out of date.  It caught up the watchlist just fine.

Enjoy!

**Comment by inject3d** [comment]
Awesome! Thank you so much!
